import { chromium } from 'playwright';
const SP=process.env.SP, KEY=process.env.KEY;
const b=await chromium.launch({channel:'chrome'});
const p=await b.newPage({viewport:{width:390,height:844}});
p.on('dialog',d=>d.dismiss());
await p.goto('http://localhost:4173/',{waitUntil:'networkidle'}); await p.waitForTimeout(1200);
await p.click('#settingsBtn'); await p.waitForTimeout(300);
await p.fill('#apiKey', KEY);
await p.setInputFiles('#pdfInput', SP+'/vendor-book.pdf'); await p.waitForTimeout(4000);
await p.click('#saveSettings'); await p.waitForTimeout(400);
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await p.setInputFiles('#frontInput', SP+'/tolfera.jpg'); await p.waitForTimeout(1200);
await p.click('#scanBtn');
await p.waitForSelector('.result-body h3, .result-body p',{timeout:90000});
await p.waitForTimeout(2500);
const txt=await p.evaluate(()=>document.getElementById('resultBody').innerText.trim());
console.log('--- CURRENT BEHAVIOUR ---'); console.log(txt.slice(0,450));
console.log('\nmentions TUFFAN (the equivalent):', /TUFFAN/i.test(txt));
await b.close();
